### ISSUE TITLE
Create login and signup pages.

### ISSUE THREAD

**Issue by danbergeron3** [BreadBoxOrg/breadbox-web#14]
# General Description
Add in the Sign in page like the one in the Figma Design.
<br />
## Proposed Solution
<enter here\>
### Checklist
<br />

- [x] Add BreadBox Logo.
- [x] Create Sign Up Button.
- [x] Create Sign In Button.
- [x] Create Footer with Nav Links
- [x] CSS Styling
- [x] Redirect Buttons to Main Dashboard(for now)

**Comment by jordyguz10** [comment]
Got the sign up page foundation and CSS Styling. Currently Working on Button Redirecting to the Main Dashboard. This is a placeholder for the Google OAuth Sign In/Sign Up

**Comment by jordyguz10** [comment]
Got the Login Button to Redirect to Dashboard. Had to restructure the Dashboard page and styling to fix the margin
