### ISSUE TITLE
Research and design finances screen functionality.

### ISSUE THREAD

**Issue by shivy02** [BreadBoxOrg/breadbox-web#22]

**Comment by callbacked** [comment]
Update: 4 out of the 6 widgets have been added thus far based off the figma implmentation, what currently is being worked on at the moment are the 'Investment Goals' widget and the 'Asset Details' widget

<img width="1270" alt="image" src="https://github.com/BreadBoxOrg/breadbox-web/assets/117959902/cebe1bd2-d0aa-4eab-a62e-74cb8b326506">


For context about 'Asset Details' I am trying to pull any stocks/crypto found in a user's linked brokerage account and display it as a line chart with options to switch between what they want to see, something similar (but very simplifed) to this

![image](https://github.com/BreadBoxOrg/breadbox-web/assets/117959902/45eec124-0030-4c9d-a023-1de5b99ab83a)


Found an API called [Finnhub](https://finnhub.io) which is free and rate limited to 30 calls/sec and I plan on using that alonogside recharts for the visualization once i get a good look at the docs.


Alot of refactoring and styling is pending but I feel confident that much of the frontend side will be ready for alpha, and will just be a matter of plugging in with our API's :)

**Comment by callbacked** [comment]
![firefox_ZFpc8T8O46](https://github.com/BreadBoxOrg/breadbox-web/assets/117959902/fa7fa9c3-d641-4682-8943-bacc23ff3c2c)

Investments Goal now pending

**Comment by callbacked** [comment]
![2eJjWiLQS8](https://github.com/BreadBoxOrg/breadbox-web/assets/117959902/074f4e4c-8562-4e2c-ab94-af8cfd840f7e)

Work on the Investments Goal widget has been started today and got the radial bar chart working, more or less I want it to resemble my sketch that I drew for it (assuming I could even overlay two recharts components on top of each other) -- but things so far have been going well and a ton of css styling and refactoring will be left (on top of hooking stuff with the backend) after this widget is done.

![image](https://github.com/BreadBoxOrg/breadbox-web/assets/117959902/104869d7-46f6-4abe-937b-e8a0ed0cd8c8)


_(realized I wrote "goals" and not "goal" lmao but that will change)_

**Comment by callbacked** [comment]
closed, foundation for this is set now -- styling is missing
