### ISSUE TITLE
Integrate Plaid Link

### ISSUE THREAD

**Issue by shivy02** [BreadBoxOrg/breadbox-web#30]
# General Description
Plaid requires a link with it and the client on top of a link with the server, to gain access to the development sandbox. This first step in plaid integration is full filling this. Once completed we should have access to the endpoints.
<br />
Create a plaid account to gain access to the api keys and Docs. Use a simple html file as a frontend, to establish the client side endpoint.
Start in the server file and establish routes to the `ceate_linkToken` endpoint, then a route to the `exchange_token ` . If the connection hits all these endpoints without error a connection should be established with plaid, and the other endpoints can be testested and brought in.
<enter here\>
### Checklist
<br />

- [x] Create plaid organization 
- [x] Build Mock Fronted 
- [x] Build server token endpoints
- [x] Test the a token is created, then probe other endpoints

**Comment by danbergeron3** [comment]
Ensure that the key in the `.env` is set to sandbox key. Also important when configuring ensure you are using the correct version of plaid.

**Comment by danbergeron3** [comment]
Plaid use requires the following libraries

-  `dotenv`
-  `express`
-  `const { Configuration, PlaidApi, Products, PlaidEnvironments} = require('plaid');`
-  `util`
- `body-parser`
- `moment`
- `cors`

**Comment by danbergeron3** [comment]
We successfully connected and started probing endpoints
